# TODO: add pnpm package-ecosystem when available.
# See https://github.com/dependabot/dependabot-core/issues/1736
# for progress on pnpm support
version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 3
