import { NpcSideQuest } from '@src/components'
import { npcs } from '@src/data'
import { Npc } from '@src/types'
import { GetStaticProps } from 'next'
import Head from 'next/head'

type PageProps = {
  data: Npc[]
}

export default function Home({ data }: PageProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {data.map((npc) => (
        <NpcSideQuest key={npc.id} data={npc} />
      ))}
    </>
  )
}

export const getStaticProps: GetStaticProps = async () => {
  return {
    props: { data: npcs },
  }
}
